-- =========================================================
-- NOVA — Supabase schema for the static (serverless) build
--
-- Applies to a Supabase project. Creates the relational tables
-- used directly from the browser via the anon/publishable key,
-- with Row Level Security (RLS) that separates:
--   PUBLIC  → read active products & settings, create own orders
--   ADMIN   → products/orders/settings CRUD + storage (Auth user)
--
-- Apply via the Supabase SQL editor or scripts/setup-supabase.js
-- =========================================================

-- Remove any pre-existing policies from earlier attempts so only the ones
-- defined below apply (policies OR together, so leftovers would open holes).
DO $$
DECLARE r RECORD;
BEGIN
  FOR r IN
    SELECT p.policyname, p.tablename
    FROM pg_policies p
    WHERE p.schemaname = 'public'
      AND p.tablename IN ('products', 'orders', 'settings')
  LOOP
    EXECUTE format('DROP POLICY IF EXISTS %I ON public.%I', r.policyname, r.tablename);
  END LOOP;
END
$$;

-- ---------- products (the full product object lives in `data` jsonb) ----------
CREATE TABLE IF NOT EXISTS public.products (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  data       JSONB NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ---------- orders (guest checkout + admin management) ----------
CREATE TABLE IF NOT EXISTS public.orders (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sid        TEXT UNIQUE,
  status     TEXT NOT NULL DEFAULT 'pending',
  product_id INTEGER,
  qty        INTEGER,
  total      NUMERIC,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  data       JSONB NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_orders_status  ON public.orders (status);
CREATE INDEX IF NOT EXISTS idx_orders_sid     ON public.orders (sid);
CREATE INDEX IF NOT EXISTS idx_orders_created ON public.orders (created_at);

-- backfill if the tables pre-existed from an older attempt without these columns
ALTER TABLE public.orders  ADD COLUMN IF NOT EXISTS qty   INTEGER;
ALTER TABLE public.orders  ADD COLUMN IF NOT EXISTS total NUMERIC;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT now();

-- sid needs a unique constraint for ON CONFLICT (sid) inside guest_upsert_order
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint
                 WHERE conrelid = 'public.orders'::regclass
                   AND contype = 'u'
                   AND conname = 'orders_sid_key') THEN
    ALTER TABLE public.orders ADD CONSTRAINT orders_sid_key UNIQUE (sid);
  END IF;
END
$$;

-- ---------- settings (key/value; value is JSON) ----------
CREATE TABLE IF NOT EXISTS public.settings (
  key   TEXT PRIMARY KEY,
  value JSONB NOT NULL
);

-- ---------- admin accounts (maps a Supabase Auth user to store admin) ----------
CREATE TABLE IF NOT EXISTS public.nova_admin (
  id         UUID PRIMARY KEY,
  email      TEXT NOT NULL,
  name       TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ---------- admin helper: is the current user a store admin? ----------
CREATE OR REPLACE FUNCTION public.is_nova_admin()
RETURNS boolean
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
STABLE
AS $$
  SELECT EXISTS (SELECT 1 FROM public.nova_admin WHERE id = auth.uid())
$$;

-- ---------- receipt view: guests may read ONLY their own order receipt ----------
-- (id/code/status/sid — no customer PII). Security definer (view owner) so it
-- bypasses base-table RLS without exposing `orders.data`.
CREATE OR REPLACE VIEW public.v_order_receipt
AS SELECT id, ('#' || id) AS code, sid, status, product_id,
          created_at, updated_at
     FROM public.orders;

-- ---------- privileges ----------
GRANT USAGE ON SCHEMA public TO anon, authenticated;
GRANT SELECT ON public.products, public.settings, public.v_order_receipt TO anon, authenticated;
GRANT INSERT, SELECT, UPDATE ON public.orders TO anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.products TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.settings TO authenticated;

-- ---------- RLS ----------
ALTER TABLE public.products    ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders      ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.settings    ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.nova_admin  ENABLE ROW LEVEL SECURITY;

-- products: everyone may read; only admins may write.
DROP POLICY IF EXISTS "products public read" ON public.products;
CREATE POLICY "products public read" ON public.products
  FOR SELECT USING (true);

DROP POLICY IF EXISTS "products admin insert" ON public.products;
CREATE POLICY "products admin insert" ON public.products
  FOR INSERT TO authenticated WITH CHECK (public.is_nova_admin());

DROP POLICY IF EXISTS "products admin update" ON public.products;
CREATE POLICY "products admin update" ON public.products
  FOR UPDATE TO authenticated USING (public.is_nova_admin()) WITH CHECK (public.is_nova_admin());

DROP POLICY IF EXISTS "products admin delete" ON public.products;
CREATE POLICY "products admin delete" ON public.products
  FOR DELETE TO authenticated USING (public.is_nova_admin());

-- orders: admins may do everything; guests may only INSERT/UPDATE rows that
-- carry a `sid` (their own checkout session — the sid is a UUID token that is
-- NOT enumerable, and guests have no SELECT, so they never read other orders).
-- NOTE: admin policies are declared per-command (NOT `FOR ALL`): with `FOR ALL`
-- the UPDATE with-check of the admin policy gets ANDed into the scan filter and
-- silently blocks guest updates (rows that only satisfy the guest policy).
DROP POLICY IF EXISTS "orders admin select" ON public.orders;
CREATE POLICY "orders admin select" ON public.orders
  FOR SELECT TO authenticated USING (public.is_nova_admin());

DROP POLICY IF EXISTS "orders admin insert" ON public.orders;
CREATE POLICY "orders admin insert" ON public.orders
  FOR INSERT TO authenticated WITH CHECK (public.is_nova_admin());

DROP POLICY IF EXISTS "orders admin update" ON public.orders;
CREATE POLICY "orders admin update" ON public.orders
  FOR UPDATE TO authenticated USING (public.is_nova_admin()) WITH CHECK (public.is_nova_admin());

DROP POLICY IF EXISTS "orders admin delete" ON public.orders;
CREATE POLICY "orders admin delete" ON public.orders
  FOR DELETE TO authenticated USING (public.is_nova_admin());

DROP POLICY IF EXISTS "orders guest insert" ON public.orders;
CREATE POLICY "orders guest insert" ON public.orders
  FOR INSERT WITH CHECK (sid IS NOT NULL);

-- Order updates by guests go through this RPC (not a filtered UPDATE):
-- PostgreSQL's RLS planner constant-folds filtered UPDATEs to "false" when a
-- guest-usable UPDATE policy exists, silently zeroing guest order updates.
-- This SECURITY DEFINER function lets a guest upsert ONLY the row that carries
-- their own (unguessable) sid. They never get a SELECT, so they cannot read
-- other orders, and both the "with check" and the row they can touch are
-- constrained by the sid they already know (the browser session token).
CREATE OR REPLACE FUNCTION public.guest_upsert_order(
  sid_in   text,
  status_in text DEFAULT NULL,
  qty_in    integer DEFAULT NULL,
  total_in  numeric DEFAULT NULL,
  payload   jsonb  DEFAULT NULL
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  oid integer;
BEGIN
  IF sid_in IS NULL OR sid_in = '' THEN
    RAISE EXCEPTION 'sid required';
  END IF;
  INSERT INTO public.orders AS o
    (sid, status, qty, total, data, updated_at)
  VALUES
    (sid_in, COALESCE(status_in, 'pending'), COALESCE(qty_in, 1),
     COALESCE(total_in, 0), COALESCE(payload, '{}'::jsonb), now())
  ON CONFLICT (sid) DO UPDATE SET
    status    = EXCLUDED.status,
    qty       = EXCLUDED.qty,
    total     = EXCLUDED.total,
    data      = EXCLUDED.data,
    updated_at = now()
  RETURNING o.id INTO oid;
  RETURN jsonb_build_object('id', oid);
END
$$;

REVOKE ALL ON FUNCTION public.guest_upsert_order(text, text, integer, numeric, jsonb) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.guest_upsert_order(text, text, integer, numeric, jsonb) TO anon, authenticated;

-- settings: everyone may read (store config); only admins write.
DROP POLICY IF EXISTS "settings public read" ON public.settings;
CREATE POLICY "settings public read" ON public.settings
  FOR SELECT USING (true);

DROP POLICY IF EXISTS "settings admin insert" ON public.settings;
CREATE POLICY "settings admin insert" ON public.settings
  FOR INSERT TO authenticated WITH CHECK (public.is_nova_admin());

DROP POLICY IF EXISTS "settings admin update" ON public.settings;
CREATE POLICY "settings admin update" ON public.settings
  FOR UPDATE TO authenticated USING (public.is_nova_admin()) WITH CHECK (public.is_nova_admin());

DROP POLICY IF EXISTS "settings admin delete" ON public.settings;
CREATE POLICY "settings admin delete" ON public.settings
  FOR DELETE TO authenticated USING (public.is_nova_admin());

-- nova_admin: no policies → only the security-definer helper / superuser can read it.

-- ---------- Supabase Storage bucket: product-images ----------
-- Public read (storefront images) + admin-only upload/delete.
DO $$
DECLARE
  bid TEXT;
BEGIN
  SELECT id INTO bid FROM storage.buckets WHERE name = 'product-images';
  IF bid IS NULL THEN
    INSERT INTO storage.buckets (id, name, public) VALUES ('product-images', 'product-images', true);
  ELSE
    UPDATE storage.buckets SET public = true WHERE id = bid;
  END IF;
END
$$;

DROP POLICY IF EXISTS "nova images public read" ON storage.objects;
CREATE POLICY "nova images public read" ON storage.objects
  FOR SELECT USING (bucket_id = 'product-images');

DROP POLICY IF EXISTS "nova images admin insert" ON storage.objects;
CREATE POLICY "nova images admin insert" ON storage.objects
  FOR INSERT TO authenticated
  WITH CHECK (bucket_id = 'product-images' AND public.is_nova_admin());

DROP POLICY IF EXISTS "nova images admin update" ON storage.objects;
CREATE POLICY "nova images admin update" ON storage.objects
  FOR UPDATE TO authenticated
  USING (bucket_id = 'product-images' AND public.is_nova_admin())
  WITH CHECK (bucket_id = 'product-images' AND public.is_nova_admin());

DROP POLICY IF EXISTS "nova images admin delete" ON storage.objects;
CREATE POLICY "nova images admin delete" ON storage.objects
  FOR DELETE TO authenticated
  USING (bucket_id = 'product-images' AND public.is_nova_admin());